# Generated by Django 2.2.3 on 2019-07-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCount',
        ),
    ]
